name: XSignsPro
main: XSignsPro\Main
version: 2.0.0
api: 
- 1.0.0
- 1.12.0
- 2.0.0
- 2.1.0
- 3.0.0
- 3.0.1
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 4.0.0
- 4.0.1
- 5.0.0
- 6.0.0
author: SnowXxm
softdepend: ["ZXDAKernel"]

commands: 
  xsp:
    description: "［XSignsPro］总指令"
